site_name: Zaphenath
site_url: https://zaphenath.astervia.tech

theme:
  name: material

  favicon: assets/images/favicon-blue.png
  logo: assets/images/favicon.png

  custom_dir: overrides

  features:
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Astervia/zaphenath
    - icon: fontawesome/solid/bolt
      link: support/plans.md

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Installation: getting-started/installation.md
      - Deployment: getting-started/deployment.md
  - Contracts:
      - Zaphenath: contracts/zaphenath.md
      - Role: contracts/role.md
      - Custodian: contracts/custodian.md
      - KeyData: contracts/keydata.md
  - Usage:
      - Roles and Permissions: usage/roles.md
      - Ping Mechanism: usage/ping.md
      - Key Lifecycle: usage/key-lifecycle.md
      - Examples: usage/examples.md
  - Testing:
      - Test Coverage: testing/overview.md
      - Writing Tests: testing/writing-tests.md

  - Support:
      - Plans: support/plans.md
      - Consulting: support/consulting.md
      - FAQ: support/faq.md
  - Reference:
      - Changelog: reference/changelog.md
